#!/usr/bin/env Rscript
# 00_build_lexicon.R -------------------------------------------------------
# Purpose: create the initial (and optionally expanded) certainty vs.
#          uncertainty lexicon for Study 2 qualitative analysis.
# Author : Auto-generated by AI assistant, 2025-06-29
# -------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(tidyverse)
})

# -------------------------------------------------------------------------
# 1. Manually curated seed lists  -----------------------------------------
# These terms come directly from key career-development theories:
#   • Identity Status (Marcia, 1966)
#   • Social Cognitive Career Theory (Lent et al., 1994)
#   • Career Indecision literature (Germeijs & Verschueren, 2006)
# Feel free to edit / extend as literature review progresses.
# -------------------------------------------------------------------------

seed_certain <- c(
  "decided", "certain", "sure", "committed", "confident", "definite",
  "determined", "resolved", "clear", "chosen"
)

seed_uncertain <- c(
  "unsure", "uncertain", "maybe", "probably", "possibly", "not sure",
  "don\'t know", "still exploring", "undecided", "hesitant",
  "nervous", "worried", "fear", "doubt", "guess"
)

lexicon_seed <- tibble(
  term = c(seed_certain, seed_uncertain),
  category = rep(c("certain", "uncertain"),
                 times = c(length(seed_certain), length(seed_uncertain)))
)

# -------------------------------------------------------------------------
# 2. (Optional) semantic-expansion section --------------------------------
# Heavy-weight embedding expansion is skipped on first pass.  To enable:
#   • Place a pre-trained GloVe or FastText .txt file in data/embeddings/
#   • Uncomment the section below.
# -------------------------------------------------------------------------

expanded_lexicon <- lexicon_seed  # default

# Attempt auto-expansion if embedding file is present -----------------------
embed_path <- 'data/embeddings/glove.6B.300d.txt'
if (file.exists(embed_path)) {
  message('🔍 Embedding file detected — expanding lexicon…')
  suppressPackageStartupMessages(library(text2vec))
  glove <- read.table(embed_path, quote = "", comment.char = "", fill = TRUE,
                      col.names = c('term', paste0('V', 1:300)))
  vocab <- glove$term
  mat   <- as.matrix(glove[ , -1])
  rownames(mat) <- vocab

  get_nns <- function(w, top_n = 25, cos_thresh = 0.45) {
    if (!w %in% rownames(mat)) return(character())
    target <- mat[w, , drop = FALSE]
    sims   <- text2vec::sim2(x = mat, y = target, method = 'cosine', norm = 'l2')[ , 1]
    nn     <- sort(sims, decreasing = TRUE)
    nn     <- nn[nn >= cos_thresh]
    setdiff(names(nn)[seq_len(min(top_n, length(nn)))], w)
  }

  new_terms_c  <- unique(unlist(lapply(seed_certain,   get_nns)))
  new_terms_uc <- unique(unlist(lapply(seed_uncertain, get_nns)))

  expanded_lexicon <- bind_rows(
    lexicon_seed,
    tibble(term = new_terms_c,  category = 'certain'),
    tibble(term = new_terms_uc, category = 'uncertain')
  ) %>% distinct(term, .keep_all = TRUE)

  message('📈 Lexicon expanded from ', nrow(lexicon_seed), ' to ', nrow(expanded_lexicon), ' terms.')
} else {
  message('ℹ️  Embedding file not found; using seed lexicon only.')
}

# -------------------------------------------------------------------------
# 3. Save outputs ----------------------------------------------------------
# -------------------------------------------------------------------------

dir.create('results', showWarnings = FALSE)
dir.create('results/study2', showWarnings = FALSE)

saveRDS(lexicon_seed,     'results/study2/seed_lexicon.rds')
saveRDS(expanded_lexicon, 'results/study2/expanded_lexicon.rds')

write_csv(lexicon_seed,     'results/study2/seed_lexicon.csv')
write_csv(expanded_lexicon, 'results/study2/expanded_lexicon.csv')

message('✅ Lexicon files written to results/study2/') 